#include "TextureLoader.h"
#include <iostream>
#include <fstream>
#include <Application.h>
#include <Systems/Logging/Logger.h>
#define STB_IMAGE_IMPLEMENTATION
#include <stb/stb_image.h>
#include <xxHash/xxhash.h>

namespace Aozora::Resources {

	Texture TextureLoader::loadTexture(const std::string& fileName, const std::string& directory, bool isSrgb)
	{
        // this is without the parent directory which we need to create unique hashes
        std::string filename = std::string(fileName);

        std::string fullPath = directory.empty() ? fileName : directory + "/" + filename;

        if (fullPath.find(".dds") != std::string::npos) {
            Log::warning("DDS loading not implemented yet: " + fullPath);
            return Texture(); 
        }

        int width, height, nrChannels;

        int usedChannels = 4;

        Texture texture;
        texture.isSrgb = isSrgb;

        if (stbi_is_hdr(fullPath.c_str())) {
            float* data = stbi_loadf(fullPath.c_str(), &width, &height, &nrChannels, 4);
            if (!data) {
                Log::error("Failed to load texture: " + fullPath);
                return Texture();
            }
            std::vector<std::vector<float>> dataV(1);
            dataV[0].resize(width * height * usedChannels);
            memcpy(dataV[0].data(), data, width * height * usedChannels * sizeof(float));
            stbi_image_free(data);
            texture.dataVector = std::move(dataV);
            texture.hasData = true;
        }
        else {
            unsigned char* data = stbi_load(fullPath.c_str(), &width, &height, &nrChannels, 4);

            if (!data) {
                Log::error("Failed to load texture: " + fullPath);
                return Texture();
            }

            std::vector<std::vector<uint8_t>> dataV(1);
            dataV[0].resize(width * height * usedChannels);
            memcpy(dataV[0].data(), data, width * height * usedChannels);
            texture.dataVector = std::move(dataV);
            texture.hasData = true;
            stbi_image_free(data);
        }

        texture.width = width;
        texture.height = height;
        texture.nrChannels = usedChannels;
        texture.name = filename;


        m_importRegistry[fullPath] = XXH64(fullPath.c_str(), fullPath.length(), 0);
        texture.hash = m_importRegistry[fullPath];
        Log::info("Successfully loaded texture: " + fullPath);
		return texture;
	}


    Texture TextureLoader::loadCubemap(const std::vector<std::string>& faces)
    {

        // should handle non hdr too but im so lazy atm
        Texture texture;
        texture.specification.config.target = Texture::TextureTarget::TEXTURE_CUBE_MAP;
        int width, height, nrChannels;

        std::vector<std::vector<float>> dataV(6);
        int i = 0;
        for (const auto& face : faces) {

            std::string filename = face;
            float* data = stbi_loadf(filename.c_str(), &width, &height, &nrChannels, 0);
            texture.width = width;
            texture.height = height;
            texture.nrChannels = nrChannels;
            if (data) {
                dataV[i].resize(width * height * nrChannels);
                memcpy(dataV[i].data(), data, width * height * nrChannels * sizeof(float));
                stbi_image_free(data);
                texture.hasData = true;
            }
            else {
                Log::error("TextureLoader::loadCubemap failed");
                stbi_image_free(data);
            }
            i++;
        }

        texture.dataVector = dataV;
        m_importRegistry[faces[0]] = XXH64(faces[0].c_str(), faces[0].length(), 0);
        texture.hash = m_importRegistry[faces[0]];
        Log::info("Successfully loaded cubemap texture");
        return texture;


    }
    // takes in the texture generated by
    Texture TextureLoader::loadIrradienceCubemap(uint32_t textureTargetID)
    {
        return Texture();
    }
}
